name: "Security & Code Quality Scan"

on:
   push:
      branches: [ "main" ]

jobs:
  static-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Run Trivy secret Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scanners: 'secret'
          exit-code: '1'

      - name: Run Trivy Code & Config Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: 'fs'
          scanners: 'config,vuln'
          exit-code: '0'
